spring:
  application:
    name: nexusIDE
  datasource:
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  data:
    jdbc:
      dialect: postgresql

logging:
  level:
    com:
      nexuside: TRACE

app:
  database:
    filename: nexusIDE.db
